name: train model (refresh run)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: train inventory model
      run: |
        cd inventory && python clear_collect.py && python train_torch_from_collect.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ark_material.onnx
        path: inventory/ark_material.onnx
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'auto update by git action (refresh run)'
        add: '.'
